import { describe, expect, it } from 'vitest';
import { agreement, ANALYSED, CASES, outcomeOf, renderMatrix } from '../scripts/context-matrix.js';

// Issue #62, Track A: the fixture list and renderer of the context matrix. The matrix itself is generated by running
// the script against the real compiler, never in CI.

describe('context matrix cases', () => {
  it('covers every case the issue names, uniquely', () => {
    const ids = [...CASES.map((c) => c.id), ...ANALYSED.map((r) => r.id)];
    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ['one-entry', 'two-entries-shared-lib', 'focused-import', 'two-folders', 'alt-cwd', 'outside-closure',
      'missing-entry', 'ambiguous-entry', 'changed-import', 'deleted-import', 'cycle', 'diamond', 'symlink-alias',
      'lone-cr', 'non-utf8', 'external-change', 'dirty-import', 'case-alias', 'editor-encoding', 'config-change']) expect(ids).toContain(id);
  });
  it('gives every case a probe that occurs in its focus file and a decision', () => {
    for (const c of CASES) {
      const focus = c.files[c.focus] ?? c.files[c.symlinks?.[c.focus] ?? ''];
      expect([c.id, focus !== undefined && Buffer.from(focus).includes(c.probe), c.decision.length > 10]).toEqual([c.id, true, true]);
    }
    for (const r of ANALYSED) expect(r.evidence).toBe('analysed');
  });
});

describe('outcomeOf', () => {
  it('normalises CLI query statuses and adapter results to one vocabulary', () => {
    expect(outcomeOf({ cli: { status: 'found', site: 'local' } })).toBe('found local');
    expect(outcomeOf({ cli: { status: 'invalid', reason: 'file-not-in-closure' } })).toBe('not in closure');
    expect(outcomeOf({ cli: { status: 'unavailable', reason: 'io' } })).toBe('unavailable (io)');
    expect(outcomeOf({ editor: { kind: 'answer', doc: { query: { status: 'found', site: 'local' } } } })).toBe('found local');
    expect(outcomeOf({ editor: { kind: 'none', reason: 'invalid position: file-not-in-closure' } })).toBe('not in closure');
    expect(outcomeOf({ editor: { kind: 'unavailable', reason: 'diagnostics' } })).toBe('unavailable (diagnostics)');
    expect(outcomeOf({ editor: { kind: 'stale', reasons: ['x'] } })).toBe('stale');
    expect(outcomeOf({ editor: { kind: 'none', reason: 'the file has a carriage return that does not end a line' } })).toBe('withheld (lone CR)');
  });
});

describe('renderMatrix', () => {
  it('renders analysed rows distinctly and escapes pipes', () => {
    const md = renderMatrix([
      { id: 'a', case: 'A', evidence: 'observed', cli: 'ok', editor: 'ok', agree: 'yes', decision: 'none' },
      { id: 'b', case: 'B|x', evidence: 'analysed', cli: '—', editor: 'drops', agree: 'n/a', decision: 'pick' },
    ]);
    expect(md).toContain('| a | A | observed | ok | ok | yes | none |');
    expect(md).toContain('| b | B\\|x | **analysed, not reproduced** | — | drops | n/a | pick |');
  });
});

const side = (outcome: string, ok: boolean, closure: string[]) => ({ outcome, ok, closure });

describe('agreement', () => {
  it('needs the same outcome, check result and closure (as a set of absolute paths)', () => {
    expect(agreement(side('found local', true, ['/r/a', '/r/b']), side('found local', true, ['/r/b', '/r/a']))).toBe('yes');
    expect(agreement(side('found local', true, ['/r/a']), side('found local', true, ['/r/a', '/r/c']))).toBe('no');
    expect(agreement(side('found local', true, ['/r/a']), side('stale', true, ['/r/a']))).toBe('no');
    expect(agreement(side('found local', false, ['/r/a']), side('found local', true, ['/r/a']))).toBe('no');
    expect(agreement(null, side('found local', true, []))).toBe('n/a');
  });
});
