import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Embeds the C runtime (packages/asterc/runtime/) in packages/asterc-self/runtime.aster as two string constants, so the
// self-hosted driver can write the runtime next to the C it emits. Run with `pnpm gen:runtime`.

/** An Aster string literal for `text`; throws on a byte outside printable ASCII, tab and newline. */
function literal(text: string): string {
  let out = '';
  for (const ch of text) {
    if (ch === '\\') out += '\\\\';
    else if (ch === '"') out += '\\"';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\t') out += '\\t';
    else if (ch >= ' ' && ch <= '~') out += ch;
    else throw new Error(`the runtime must be ASCII: cannot embed U+${ch.codePointAt(0)!.toString(16).padStart(4, '0')}`);
  }
  return `"${out}"`;
}

/** The text of runtime.aster for the runtime header `h` and source `c`. */
export function renderRuntimeAster(h: string, c: string): string {
  return [
    '// expect-library',
    '// Generated by pnpm gen:runtime from packages/asterc/runtime/; do not edit.',
    '',
    '// The text of aster_rt.h.',
    'fn runtime_h(): string {',
    `    return ${literal(h)};`,
    '}',
    '',
    '// The text of aster_rt.c.',
    'fn runtime_c(): string {',
    `    return ${literal(c)};`,
    '}',
    '',
  ].join('\n');
}

const read = (name: string) => readFileSync(new URL(`../packages/asterc/runtime/${name}`, import.meta.url), 'utf8');

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL('../packages/asterc-self/runtime.aster', import.meta.url), renderRuntimeAster(read('aster_rt.h'), read('aster_rt.c')));
}
